-- MusicaSpace Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id text not null,
  title text not null,
  artist text,
  song_key text,
  bpm integer,
  created_at timestamptz not null default now(),
  unique(user_id, song_id)
);

create table if not exists public.practice_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tool text not null,
  score integer default 0,
  hits integer default 0,
  misses integer default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.favorites enable row level security;
alter table public.practice_sessions enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "favorites own rows" on public.favorites;
create policy "favorites own rows" on public.favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "practice own rows" on public.practice_sessions;
create policy "practice own rows" on public.practice_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);